name: Spelling & Styles

on:
  push:
    branches:
    - main
    paths:
    - '**.md'
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Vale Linting
      uses: errata-ai/vale-action@v2
      with:
        files: '["introduction/", "infrastructure/", "measuring/", "governance/"]'
        vale_flags: "--glob=*.md"
        filter_mode: added
        debug: true
